#include <stdlib.h>
#include <stdio.h>

#include "syscalls.h"
#include "strace.h"

bool_t print_null_pointer(unsigned long int value, type_t type)
{
	type_t pointer_types[] = {
		AIO_CONTEXT_T_P, CHAR_P, CPU_SET_T_P, FD_SET_P, GID_T_P, INT_P,
		LOFF_T_P, LONG_P, OFF_T_P, SIGINFO_T_P, SIGSET_T_P, SIZE_T_P,
		SOCKLEN_T_P, STACK_T_P, STRUCT_EPOLL_EVENT_P,
		STRUCT_GETCPU_CACHE_P, STRUCT_IOCB_P, STRUCT_IOCB_PP,
		STRUCT_IOVEC_P, STRUCT_IO_EVENT_P, STRUCT_ITIMERSPEC_P,
		STRUCT_ITIMERVAL_P, STRUCT_KERNEL_SYM_P, STRUCT_KEXEC_SEGMENT_P,
		STRUCT_LINUX_DIRENT_P, STRUCT_MMSGHDR_P, STRUCT_MQ_ATTR_P,
		STRUCT_MSGHDR_P, STRUCT_MSQID_DS_P, STRUCT_NFSCTL_ARG_P,
		STRUCT_OLD_LINUX_DIRENT_P, STRUCT_PERF_EVENT_ATTR_P,
		STRUCT_POLLFD_P, STRUCT_RLIMIT_P, STRUCT_ROBUST_LIST_HEAD_P,
		STRUCT_ROBUST_LIST_HEAD_PP, STRUCT_RUSAGE_P,
		STRUCT_SCHED_PARAM_P, STRUCT_SEMBUF_P, STRUCT_SHMID_DS_P,
		STRUCT_SIGACTION_P, STRUCT_SIGEVENT_P, STRUCT_SOCKADDR_P,
		STRUCT_STATFS_P, STRUCT_STAT_P, STRUCT_SYSINFO_P,
		STRUCT_TIMESPEC_P, STRUCT_TIMEVAL_P, STRUCT_TIMEX_P,
		STRUCT_TIMEZONE_P, STRUCT_TMS_P, STRUCT_USER_DESC_P,
		STRUCT_USTAT_P, STRUCT_UTIMBUF_P, STRUCT_UTSNAME_P,
		STRUCT_VM86_STRUCT_P, STRUCT___SYSCTL_ARGS_P, TIMER_T_P,
		TIME_T_P, UID_T_P, UNION_NFSCTL_RES_P, UNSIGNED_CHAR_P,
		UNSIGNED_LONG_P, VOID_P, VOID_PP
	};
	size_t i;

	if (value != 0)
		return (FALSE);

	for (i = 0; i < ARRAY_SIZE(pointer_types); i++)
	{
		if (type == pointer_types[i])
		{
			printf("NULL");
			return (TRUE);
		}
	}

	return (FALSE);
}
